apiVersion: apps/v1
kind: Deployment
metadata: 
  name: zhooze
  labels:
    app: zhooze
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: zhooze
  template:
    metadata:
      labels:
        app: zhooze
    spec:
      containers:
        - name: zhooze
          image: akhi9550/zhooze:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: zhooze-service
spec:
  selector:
    app: zhooze
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
